scriptencoding utf-8

if !has('nvim')
  unlet! skip_defaults_vim
  source $VIMRUNTIME/defaults.vim
endif

if has('nvim')
  call plug#begin('~/.local/share/nvim/plugged')
else
  call plug#begin('~/.vim/plugged')
endif

Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'

Plug 'easymotion/vim-easymotion'

Plug 'sgur/vim-editorconfig'

Plug 'arcticicestudio/nord-vim'
Plug 'jeffkreeftmeijer/vim-dim'

Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-unimpaired'
"Plug 'tpope/vim-eunuch' ":SudoWrite
Plug 'tpope/vim-repeat'

Plug 'scrooloose/nerdtree'
let NERDTreeShowHidden=1

Plug 'markonm/traces.vim'
Plug 'michaeljsmith/vim-indent-object'

Plug 'ntpeters/vim-better-whitespace'

"Plug 'Yggdroot/indentLine'
"let g:indentLine_char = '|'

" Plug 'scrooloose/nerdtree'
" autocmd vimenter * NERDTree
" autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif
" let g:NERDTreeAutoDeleteBuffer = 1
" let g:NERDTreeMinimalUI = 1
" let g:NERDTreeDirArrows = 1
" let g:NERDTreeStatusline = 'NERD>'
" let g:NERDTreeIgnore = ['.DS_Store']

" Plug 'justinmk/vim-dirvish'

" Plug 'digitaltoad/vim-pug'

call plug#end()

" fzf
let $FZF_DEFAULT_COMMAND= 'rg --files'
let g:fzf_layout = { 'down': '~100%' }

" netrw
let g:netrw_liststyle = 3
let g:netrw_banner = 0
let g:netrw_list_hide= '.DS_Store'

"grep
"set grepprg=rg\ --vimgrep\ --no-heading\ --smart-case
set grepprg=rg\ --vimgrep\ --no-heading

" match
"runtime macros/matchit.vim

"colorscheme nord
"colorscheme grim
colorscheme default
syntax on

"set clipboard=unnamed

set mouse-=a

set nobackup
set nowritebackup
set noswapfile

set fileencodings=ucs-bom,utf-8,korea,default,latin1
set termencoding=utf8

set laststatus=2
set statusline=
set statusline+=%03.3n\  "buffer number
set statusline+=%<        "truncate if long
set statusline+=%f\       "filename
set statusline+=%h%m%r    "flag
set statusline+=%=        "right align remainder
set statusline+=%-14.(%l,%c%V%)\   "line, char
set statusline+=%P        "file position

set tabstop=2
set autoindent
set nocindent
set shiftwidth=2
set expandtab
set smarttab

"set textwidth=80

set nowrap

set number
"set relativenumber

set cursorline
"set cursorcolumn

"set list
"set listchars=tab:\|\ ,trail:·

set selection=exclusive

set ignorecase
set smartcase

set hlsearch
set incsearch
"set nowrapscan

set hidden

"hi MatchParen ctermfg=white
"hi MatchParen ctermbg=cyan

" comment
autocmd filetype * setlocal formatoptions-=c formatoptions-=r formatoptions-=o

autocmd quickfixcmdpost [^l]* nested cwindow
autocmd quickfixcmdpost    l* nested lwindow


" Keymaps

let mapleader = " "

imap jj <Esc>

" format paragraph
vmap Q gq
nmap Q gqap

nmap sl <Plug>(easymotion-lineforward)
nmap sj <Plug>(easymotion-j)
nmap sk <Plug>(easymotion-k)
nmap sh <Plug>(easymotion-linebackward)
nmap sa <Plug>(easymotion-jumptoanywhere)
nmap sf <Plug>(easymotion-f)

nnoremap S :bprevious<CR>
vnoremap S :bprevious<CR>

nnoremap K :bnext<CR>
vnoremap K :bnext<CR>

nnoremap Y y$

nnoremap zj o<Esc>k
nnoremap zk O<Esc>j

"nnoremap <Leader>a
"nnoremap <Leader>A

nnoremap <Leader>b :buffer #<CR>
nnoremap <Leader>B :Buffers<CR>

nnoremap <Leader>c :cd %:p:h<CR>:pwd<CR>
"nnoremap <Leader>C

nnoremap <Leader>d :bdelete<CR>
"nnoremap <Leader>D

nnoremap <Leader>e :e.<CR>
"nnoremap <Leader>E

"nnoremap <Leader>f
nnoremap <Leader>F :Files<CR>

nnoremap <Leader>g :silent grep<Space>
nnoremap <Leader>G :GFiles<CR>

"nnoremap <Leader>h
"nnoremap <Leader>H

"nnoremap <Leader>i
"nnoremap <Leader>I

"nnoremap <Leader>j
"nnoremap <Leader>J

"nnoremap <Leader>k
"nnoremap <Leader>K

nnoremap <Leader>l :ls<CR>:b<space>
"nnoremap <Leader>L

nnoremap <Leader>m :mksession!<CR>
"nnoremap <Leader>M

nnoremap <Leader>n :NERDTreeToggle<CR>
nnoremap <Leader>N :NERDTreeFind<CR>

"nnoremap <Leader>o
"nnoremap <Leader>O

nnoremap <Leader>p "*p
"nnoremap <Leader>P

"nnoremap <Leader>q
"nnoremap <Leader>Q

"nnoremap <Leader>r
"nnoremap <Leader>R

"nnoremap <Leader>s
"nnoremap <Leader>S

"nnoremap <Leader>t
"nnoremap <Leader>T

"nnoremap <Leader>u
"nnoremap <Leader>U

"nnoremap <Leader>v :Dirvish<CR>
"nnoremap <Leader>V

"nnoremap <Leader>w
"nnoremap <Leader>W

nnoremap <Leader>x :cclose<CR>
"nnoremap <Leader>X

nnoremap <Leader>y "*y
vnoremap <Leader>y "*y
"nnoremap <Leader>Y

"nnoremap <Leader>z
"nnoremap <Leader>Z

nnoremap <tab>oi :e ~/.ideavimrc<cr>
nnoremap <tab>ot :e ~/.tmux.conf<cr>
nnoremap <tab>ov :e ~/.vim/vimrc<cr>

nnoremap <tab>, :e $MYVIMRC<cr>
nnoremap <tab>. :source $MYVIMRC<cr>

nnoremap <C-h> <C-w><C-w>
"nnoremap <C-j>
"nnoremap <C-k>

nnoremap <silent> <C-l> :<C-u>nohlsearch<CR><C-l>

nnoremap <C-w>3 :resize 30<CR>
nnoremap <C-w>4 :resize 40<CR>
nnoremap <C-w>5 :resize 50<CR>

"vnoremap <C-c> "+y
"nnoremap + "*
"vnoremap + "*

